service: SendToQueue

custom:
  settings:
    SqsUrl: https://sqs.eu-west-2.amazonaws.com/778080946765/AFJobSync.fifo

provider:
  name: aws
  runtime: nodejs10.x
  stage: live
  region: eu-west-2
  environment: ${self:custom.settings}
  deploymentBucket:
      name: sls-core-deployment
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:sendMessage
      Resource: arn:aws:sqs:eu-west-2:778080946765:AFJobSync.fifo

functions:
  SendToSQS:
    handler: handler.sendToSQS
